### ISSUE TITLE
add any keyCode for support

### ISSUE THREAD

**Issue by deemoding** [malad1211/Mania-Cat#1]
Hello.I set the keycode 59. But there is no effect when I press the semicolon. Can you add more keyCode for support?

By the way, Can mania cat support for other controler such as iidx controler?

**Comment by malad1211** [comment]
59 is the virtual keycode for 'Y', 186 is for semicolon. There should be a config .exe that you can run in the download that sets the corresponding keys so you don't have to look them up online.

I think most controllers convert to normal keyboard input so it would work fine.

**Comment by deemoding** [comment]
> 
> 
> 59 is the virtual keycode for 'Y', 186 is for semicolon. There should be a config .exe that you can run in the download that sets the corresponding keys so you don't have to look them up online.
> 
> I think most controllers convert to normal keyboard input so it would work fine.

Maybe it's a bug for javascript. I use javascript to get keyCode on my laptop, and 59 is for semicolon(Actually you are right).

As for your config.exe, there are some errors when I run it.

Can't find VCRUNTIME140D.dll, MSVCP140D.dll and ucrtbased.dll

**Comment by malad1211** [comment]
Yeah I think I messed up compiling that config.exe since a few other people can't run it too. Thanks for the error message.
